spring:
  data:
    mongodb:
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      host: localhost
      port: 27017
      database: ${MONGODB_CUSTOMER_SERVICE_DB}
      authentication-database: ${MONGODB_CUSTOMER_SERVICE_AUTH_DB}
server:
  port: 8090


