spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
server:
  port: 8070

application:
  config:
    customer-url: http://localhost:8090/api/v1/customers
    product-url: http://localhost:8050/api/v1/products
    payment-url: http://localhost:8010/api/v1/payments